# -*- coding: utf-8 -*-
"""
/***************************************************************************
 gto_main
                                 A QGIS plugin
 Task organizer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-05-25
        copyright            : (C) 2018 by ms.GIS Ltd
        email                : contact@msgis.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load gto_main class from file gto_main.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gto_plugin import gtoPlugin
    return gtoPlugin(iface)
